### ISSUE TITLE
question about final fit in MGWR class? 

### ISSUE THREAD

**Issue by ljwolf** [pysal/mgwr#1]
https://github.com/pysal/gwr_private/blob/2e666645a8fd0acf4eeec7ee18844db9f4ba484c/mgwr/gwr.py#L1057

Why do we do this second pass on the fit after already having the final XB values from the backfitting algorithim in Sel_BW? 

I thought that the last iteration of the backfit is the "converged" values of each smooth?

**Comment by TaylorOshan** [comment]
Final fit is now carried over from model estimation
