### ISSUE TITLE
Redundant calculation of Aj

### ISSUE THREAD

**Issue by Ziqi-Li** [pysal/mgwr#10]
https://github.com/pysal/gwr_private/blob/8665c8ce2459c04ba5cd9d923ac1064ba9d81729/gwr/search.py#L220
```
for j in range(n):
    Wj = np.diag(optim_model.W[j])
    XtW = np.dot(temp_X.T, Wj)
    XtWX_inv = np.linalg.inv(np.dot(XtW, temp_X))
    P = np.dot(XtWX_inv, XtW)
    Aj[j,:] = temp_X[j,:] * P
```
This loop here basically calculates hat matrix of `optim_model = gwr_func(temp_y, temp_X, bw)` row by row, we could just let `Aj = optim_model.S` to avoid the for loop and get a big speed-up.
[test](https://gist.github.com/Ziqi-Li/6c84a94f588b01fb3e19b3e06c333ae0) using GA data `np.allclose(Aj, optim_model.S)`yields all True.

@TaylorOshan

**Comment by TaylorOshan** [comment]
Aj is no longer redundant.
