### ISSUE TITLE
import libpysal error for Windows

### ISSUE THREAD

**Issue by Azad77** [pysal/mgwr#100]
ImportError                               Traceback (most recent call last)
~\miniconda3\envs\da35\lib\site-packages\libpysal\cg\alpha_shapes.py in <module>
     23 try:
---> 24     import pygeos
     25 

ImportError: No module named 'pygeos'

During handling of the above exception, another exception occurred:

NameError                                 Traceback (most recent call last)
<ipython-input-4-6a43e31b7985> in <module>
----> 1 import libpysal as ps

~\miniconda3\envs\da35\lib\site-packages\libpysal\__init__.py in <module>
     25     Tools for creating and manipulating weights
     26 """
---> 27 from . import cg
     28 from . import io
     29 from . import weights

~\miniconda3\envs\da35\lib\site-packages\libpysal\cg\__init__.py in <module>
      9 from .sphere import *
     10 from .voronoi import *
---> 11 from .alpha_shapes import *

~\miniconda3\envs\da35\lib\site-packages\libpysal\cg\alpha_shapes.py in <module>
     25 
     26     HAS_PYGEOS = True
---> 27 except ModuleNotFoundError:
     28     HAS_PYGEOS = False
     29 

NameError: name 'ModuleNotFoundError' is not defined

**Comment by Ziqi-Li** [comment]
It is more of a `libpysal` related question. I am closing now. If any other issues occur, please re-open this.
