### ISSUE TITLE
allow results.summary() to return a string or redirect

### ISSUE THREAD

**Issue by chrisg-ngis** [pysal/mgwr#108]
results.summary() always prints to stdout. 
It would be good to provide it as a string that could be piped, logged or stored anywhere.

**Comment by Ziqi-Li** [comment]
Yes! That's something that is on the to-do list, and hopefully it can be done in a week or so.

**Comment by chrisg-ngis** [comment]
Hi Zigi Li,

I have been using the python GWR library for a few weeks.
I am not very good at the stats side.
My main feedback is that I would have loved to see some examples examining Raster data.
We have data in GeoTIF which we read and perform GWR on. But there is missing data (clipped) where we have NaN so there are several issues.

  1.  How to read a GeoTIFF to a 2D raster  (rasterio)
  2.  Convert to a 1D raster as input for GWR
  3.  Get the lat lon of each point (or the xy offsets if UTM)
  4.  Remove NaN
  5.  Do GWR on cleaned array
  6.  Apply the results back to the dirty array
  7.  Reformat to a 2-D image or add as new bands and save.

I know most of this is not core to the library, but it would be of great value for people taking it up who are unfamiliar with these techniques.

Regards, Chris

**Comment by Ziqi-Li** [comment]
Hi @chrisg-ngis,

Thanks for the suggestion. However, data cleaning and preprocessing may be outside the scope of this package. I believe there should be methods available to convert a raster in `rasterio` to `GeoDataFrame`. If you have any standardised solution for demonstrating the process of feeding raster data to MGWR, please submit it as a pull request. 

Cheers

**Comment by mtralka** [comment]
#109 implements an `as_str` return option to summary methods. @chrisg-ngis does this meet your usage requirements?

**Comment by chrisg-ngis** [comment]
Hi Matthew,

That’s perfect!

Regards, Chris

**Comment by chrisg-ngis** [comment]
Hi Ziqi,

You are right it is not a core delivery for your library.
I think of it more as a tutorial on how to use it for image processes. Perhaps an article on medium.

I will have a think about how to ingest a raster.

Perhaps providing an option to ignore rows with values outside certain limits would make it easier to use by simplifying data cleaning.
So if X or y contains a NaN or out of range result, then the output result is also Nan, but its doesn’t impact the other results? I am not sure if that is even possible.

Regards, Chris
