### ISSUE TITLE
Need to restrict MGWR bandwidth search range to avoid singular matrix problem

### ISSUE THREAD

**Issue by ysm1nz** [pysal/mgwr#121]
I have a GWR that works fine with a high bandwidth but fails with the singular matrix error at a lower bandwidth. The problematic variable has only 63 non-zero values out of 35,000 but the variable is important to my analysis so I don't want to drop it. 
Is there a way to restrict the MGWR bandwidth search range for a variable?

**Comment by Ziqi-Li** [comment]
Hi @ysm1nz 
Yes, you can specify a minimum bandwidth for each covariate by passing a list of values to the `.search()` function using the `multi_bw_min` parameter. See [here](https://github.com/pysal/mgwr/blob/2a955355e31fe4a124b49ce4723335d308ee09d2/mgwr/sel_bw.py#L219) for more details.
