### ISSUE TITLE
A Error raised when I bulid a mgwr model,which is"Error displaying widget: model not found",how can I solve it?

### ISSUE THREAD

**Issue by yilvzhishi** [pysal/mgwr#122]
A Error raised when I bulid a mgwr model,which is"Error displaying widget: model not found".

This is the error page:
![image](https://user-images.githubusercontent.com/105226929/210126901-7269521e-076b-45f5-882e-35bead9cba95.png)
I'm not sure if this affects mgwr model building.
Thanks for any help!

**Comment by jGaboardi** [comment]
Can you paste in the code from the screenshot above? That will help us for debugging.

**Comment by knaaptime** [comment]
try installing/updating `ipywidgets` in that environment

**Comment by yilvzhishi** [comment]
> Can you paste in the code from the screenshot above? That will help us for debugging.

Thank you for your prompt reply.I found that is not the question of PySAL . When I use Jupyter Notebook , there is no such error . When I use other python library(like geemap) in JupyterLab,this error has occurred again.

**Comment by yilvzhishi** [comment]
> try installing/updating `ipywidgets` in that environment

I test "pip uninstall ipywidgets" and "pip install ipywidgets",But it didn't work.Maybe there is something wrong with my conda installation. I have quited the JupyterLab and rework with Jupyter Notebook.(I don't understand why JupyterLab can't but Notebook can.Thanks for your reply.

**Comment by yilvzhishi** [comment]
Record My solution to the problem.
I find that too high veision of ipywidgets causes this error.In this conda env ,the version of ipywidgets is 8.0.4,when I demote the ipywidgets with conda(conda install ipywidgets==7.6.5 -c conda-forge),Then this error disappeared!Hope this can help others with the same error.
