### ISSUE TITLE
Information about the effect of the else independent variable on the dependent variable

### ISSUE THREAD

**Issue by TongCWei** [pysal/mgwr#133]
I want to know about the effect of the else independent variable that I did not take into account in the modeling on the dependent variable  is contained in the constant term or the residual term？It's been bothering me for a long time. Thanks！

**Comment by ljwolf** [comment]
Hi Tong! 

[@ASFotheringham and @Ziqi-Li](https://doi.org/10.1080/24694452.2023.2227690) argue that the "spatially-structured" component to an omitted variable is generally captured in the intercept. A "spatially-independent" component would be captured in the residual. This is a common argument (see [Pace & LeSage from 2010](https://www.researchgate.net/profile/James-Lesage/publication/226516533_Omitted_Variable_Biases_of_OLS_and_Spatial_Lag_Models/links/02bfe510a922ff2691000000/Omitted-Variable-Biases-of-OLS-and-Spatial-Lag-Models.pdf)), that the spatial component of these models "picks up" on these spatially-structured components of an omitted variable.
