### ISSUE TITLE
How to solve the problem about the "invalid index to scalar variable" when use Sel_BW.search( ) ?

### ISSUE THREAD

**Issue by HeyAy** [pysal/mgwr#143]
I use the function "Sel_BW ()", it can run successfully. But when i use the Sel_BW.search( ),  python warns that "IndexError: invalid index to scalar variable."

**Comment by HeyAy** [comment]
Well, i solve the above problem with reshaping the np.array on the y variable.

**Comment by Ziqi-Li** [comment]
Ok great, I am closing this comment.

**Comment by T-QFL** [comment]
Ahhhhhhhh! Finally！

**Comment by WilsonZrB** [comment]
sorry, I came occur to this problem , but I dont know my XY is good or not:

X_scaled shape: (22748, 8)
y shape: (22748,)
coords shape: (22748, 2)
X_scaled dtype: float64
y dtype: float64
coords dtype: float64

above are my output of my xy shape and datatype

**Comment by marquisvictor** [comment]
I don't know if this is too late but the shape of your dependent variable (y) should be (n, 1) matrix. I would do a reshape on the y to make it a two-dimensional column matrix. Hope that helps

**Comment by Qiqian674** [comment]
> I don't know if this is too late but the shape of your dependent variable (y) should be (n, 1) matrix. I would do a reshape on the y to make it a two-dimensional column matrix. Hope that helps

omg you help me a lot！！thx so much

**Comment by marquisvictor** [comment]
my pleasure!
