### ISSUE TITLE
change imports from spreg

### ISSUE THREAD

**Issue by ljwolf** [pysal/mgwr#22]
We're having some trouble with a few imports here. 

If it's possible, can you switch from `import spreg.user_output as USER` to `from spreg import user_output as USER`? For some reason we're not sure of, our build chokes when we have imports of the general pattern:
`import package.module_name as module_alias`
instead of 
`from package import module_name as module_alias`

We need to change this in the submodule contract, but it'll be present in future releases.

**Comment by TaylorOshan** [comment]
This only applies to spreg dependencies, or needs to be changed throughout? @ljwolf

**Comment by ljwolf** [comment]
This needs to be done everywhere, but I think the only place you do it is in this `spreg` call. 

I appreciate the change; we're trying to cut down on the size of some [powerful `sed` black magic](https://github.com/pysal/pysal/blob/next/convert.py#L31) used in the build script.

**Comment by TaylorOshan** [comment]
I see, so it only applies to ``from package import module_name as module_alias`` and not to ``from package.module_name import class``, which I do quite frequently?

**Comment by ljwolf** [comment]
No; it seems to only choke on:
```python
import spreg.user_ouput as USER
```
but doesn't choke on
```python
from spreg import user_output as USER
```
or 
```python
from spreg.user_output import check_X
```

**Comment by TaylorOshan** [comment]
Ok, then I think #24  satisfies this. Will merge and close.
