### ISSUE TITLE
Inconsistent metadata info on setup.py

### ISSUE THREAD

**Issue by ocefpaf** [pysal/mgwr#25]
[`setup.py` says BSD-3-Clause](https://github.com/TaylorOshan/mgwr/blob/master/setup.py#L36) but the [license file is BSD-2-clause](https://github.com/pysal/mgwr/blob/master/LICENSE#L1).

Also, the url listed in the setup.py is [from a fork](https://github.com/pysal/mgwr/blob/master/setup.py#L16).

**Comment by jGaboardi** [comment]
addressed in #27
