### ISSUE TITLE
rebuild rights access?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/mgwr#28]
@sjsrey @ljwolf @TaylorOshan I am doing some housekeeping for `mgwr` and a build has errored out, which led me to realize that I done have permissions to restart a build on `travis` or mark issues/PRs for the repo. Is there an easy switch that can be filled to grant me those permissions?

**Comment by ljwolf** [comment]
I think so. I don't know whether this is all sorted consistently across our repositories. I think this repository was limited only to the gwr team for organizational reasons.
