### ISSUE TITLE
Large-scale data cause the server down

### ISSUE THREAD

**Issue by kkyyhh96** [pysal/mgwr#66]
When the data set has about 3000 polygons/points with more than 20 attributes, the program will make the server down. My server was shutdown because of this for several times. I was running the code on a Linux server with python 3.6, mgwr 2.0.0, more than 72 CPU cores and 300G+ memories.

**Comment by Ziqi-Li** [comment]
Hi @kkyyhh96. I am not sure which version are you currently using (I assume you might use an old version). We have applied some optimizations recently #52. For the size of the problem you are having (3000 with 20 features), the current master brach on GitHub should be able to handle it. To increase the performance, I would also suggest to install [numba](https://numba.pydata.org) via pip. Also if you are encountering any memory issue, please try increasing the [n_chunks](https://github.com/pysal/mgwr/blob/c5b6bb12de5c9757811aba68d9c5ab9fc59d3803/mgwr/gwr.py#L1520) parameters in `MGWR.fit()` to get over the memory problem.

I am closing this issue, if you are still having this problem, please let us know.
