### ISSUE TITLE
model.predict  =>  AttributeError: 'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by icefoxhz** [pysal/mgwr#85]
pred_results = model.predict(pred_coords, pred_X, scale, residuals)

pred_coords is a list,  must modify the code as follows:

![image](https://user-images.githubusercontent.com/35057092/91926948-01de7200-ed0b-11ea-94ea-51681ffea5a2.png)

**Comment by ljwolf** [comment]
Please use numpy arrays for input (X, y, and coordinates). Lists are not supported.

**Comment by icefoxhz** [comment]
ok ,  thanks
