### ISSUE TITLE
how to print the detail results of gwr

### ISSUE THREAD

**Issue by zlh1998ecnu** [pysal/mgwr#97]
hello guys. does anybody could tell me how to print the detail results of gwr? Jupyter just told me that `mgwr.gwr.GWRResults object at 0x000002043860BEB0`. Does not mgwr pkg output a file such as csv?

i am totally a rookie...  i will be grateful if someone could answer my confusion.

**Comment by Ziqi-Li** [comment]
Hi @zlh1998ecn,

Thats a good point! We could probably add a function to export the results to a csv file. At the moment, you could follow[ this notebook](https://gist.github.com/Ziqi-Li/d280ae85d2d357c091cbd0ed05b58488) to create a `pandas.DataFrame` with the local estimates and standard errors etc, and then export to a csv file.

**Comment by zlh1998ecnu** [comment]
thanks for your attention and advice.  And I think a txt file would  also helpful. I do appreciate the work you did. @Ziqi-Li
