### ISSUE TITLE
MGWR function not accepting the bw value or array

### ISSUE THREAD

**Issue by PratyushTripathy** [pysal/mgwr#98]
Creating the mgwr_model using the MGWR function requires the bandwidth parameter. However, it does not accept a value or the array as shown in the paper. The error says "AttributeError: 'numpy.ndarray' object has no attribute 'bw'" (screenshot attached). This implies that it requires the selector object as opposed to the bandwidth value or array. I passed the bandwidth selector object in place of the value and it worked! (screenshot attached)

<img width="540" alt="mgwr_bw_error" src="https://user-images.githubusercontent.com/29382796/120933661-b719dc80-c718-11eb-9f40-d74e546a536f.PNG">
<img width="498" alt="mgwr_bw_resolved" src="https://user-images.githubusercontent.com/29382796/120933662-b8e3a000-c718-11eb-9849-a9e81dc11dba.PNG">

**Comment by Ziqi-Li** [comment]
Hi @PratyushTripathy, Thats true. We need to pass the selector object when initializing an `MGWR()` object because the selector actually contains more information than just the bandwidths.
